### ISSUE TITLE
Authentifizierung erweitern Token Access und OAuth2

### ISSUE THREAD

**Issue by contaoacademy** [contaoacademy/contao-zammad-nc-api-bundle#1]
REST API mittels Token (nicht Benutzername/E-Mail und Passwort) aktivieren. Jeder Benutzer muss persönliche Access Token im Benutzerprofil erstellen.

Beispiel:

`curl -H "Authorization: Token token=YOUR_TOKEN" https://user.zammad.com/api/v1/groups`

**Comment by contaoacademy** [comment]
Ich glaube es wäre sogar noch besser, wenn es ein OAuth2 wäre.

**OAuth2 (token access)**
The Zammad API supports OAuth2 authorization. In order to create OAuth2 tokens for an external application, the Zammad user needs to create an application in the admin interface. The access token then has to be given within the HTTP header:

Example:

`curl -H "Authorization: Bearer {your_token}" https://your_zammad/api/v1/users`

**Comment by contaoacademy** [comment]
`curl_setopt($objCurl, CURLOPT_HTTPHEADER, array(
            "Authorization: Bearer " . $this->strOAuthToken,
            "content-type: application/json",
            "X-On-Behalf-Of: " . $arrTokens['form_email']
        ));`

**Comment by contaoacademy** [comment]
@alnv Wäre super, wenn du das noch machen könntest. Laut Zammad gibt das auch einen Performance-Vorteil wenn man Token nutzt anstatt Passwort.

**Comment by contaoacademy** [comment]
Die Anmeldung per Token funktioniert.
Allerdings sollte der Eintrag "Host" auch beim Token verfügbar sein.

Im Moment muss ich die Einstellung noch über Basic setzen und kann dann erst auf Token umschalten.

**Comment by alnv** [comment]
Okay, ist drin.
