### ISSUE TITLE
Erweitern um den Header X-On-Behalf-Of

### ISSUE THREAD

**Issue by contaoacademy** [contaoacademy/contao-zammad-nc-api-bundle#2]
Ich möchte, dass beim Erstellen des Tickets der ursprüngliche User erscheint.

Dazu muss der Header erweitert werden:
https://docs.zammad.org/en/latest/api-intro.html#example-curl-request-on-behalf-of-a-different-user

**Comment by contaoacademy** [comment]
`curl_setopt($objCurl, CURLOPT_HTTPHEADER, array(
            "content-type: application/json",
            "X-On-Behalf-Of: " . $arrTokens['form_email']
        ));`

**Comment by alnv** [comment]
Ist implementiert, bitte testen.

**Comment by contaoacademy** [comment]
Funktioniert
